### ISSUE TITLE
dexie-mongoify not working with latest dexie.js

### ISSUE THREAD

**Issue by nevf** [YuriSolovyov/Dexie-mongoify#13]
I've just downloaded the latest dexie.js and the latest dexie-mongoify.min.js and am getting `"TypeError: Cannot read property 'push' of undefined"`  

It appears as though quite a bit has changed in dexie.js lately

**Comment by YurySolovyov** [comment]
I'll look into it, thanks

**Comment by YurySolovyov** [comment]
In the meantime, can you try to track down last version that works?

**Comment by nevf** [comment]
Thanks for looking into it. I don't know where to get older versions of Dexie. I did have a look in the branches. 

My problem is I've just found out that my app isn't working with IndexedDb in Firefox and I'm hoping that moving to the latest version of Dexie will resolve this, but I can't because of the dexie-mongoify issue.

**Comment by YurySolovyov** [comment]
@nevf I just fixed some issues with Dexie 1.5, you can grab new dist in master. Check if it works better for you. I the meantime, I'll check Dexie 2

**Comment by YurySolovyov** [comment]
Filled the issue: https://github.com/dfahlander/Dexie.js/issues/343

**Comment by YurySolovyov** [comment]
Possible fix:

``` js
    var WriteableTable;
    if (db.WriteableTable) {
        WriteableTable = db.WriteableTable;
    } else {
        WriteableTable = db.Table;
    }

    WriteableTable.prototype.update = ...
```

**Comment by nevf** [comment]
@YurySolovyov Thanks for the Dexie 1.5 update. Unfortunately I'm still getting the same error in Firefox.

`open() error: Object { _e: Error, name: "UnknownError", message: ""The operation failed for reasons unrelated to the database itself and not covered by any other error code."", inner: DOMError, stack: "" }`

I'm unable to access the DB in Firefox Debugger - Storage as IndexedDB is not available otherwise I'd delete it and see if that resolved my issue. It could just be that the DB is screwed. I'll try a few more things.

**Comment by YurySolovyov** [comment]
@nevf also try out the branch from #14

**Comment by nevf** [comment]
@YurySolovyov Do you mean - try the `dexie-2-support` branch?

**Comment by YurySolovyov** [comment]
Yup

**Comment by nevf** [comment]
@YurySolovyov Same problem. This is seriously weird. Ok I've just tried the first Sample at https://github.com/dfahlander/Dexie.js/wiki/Dexie in jsFiddle and am getting the same error. So it would appear to be a Firefox or Dexie issue. I'll dig a bit deeper. 

Will you release an master with Dexie 2 once your Dexie issue is resolved?

**Comment by nevf** [comment]
@YurySolovyov Ok I've found this Dexie issue https://github.com/dfahlander/Dexie.js/issues/298 - I'll post there.

**Comment by nevf** [comment]
@YurySolovyov I've reinstalled Firefox and the issue has gone away. Flakey, buggy Firefox! More info @ https://github.com/dfahlander/Dexie.js/issues/298

**Comment by nevf** [comment]
@YurySolovyov I see that [](https://github.com/dfahlander/Dexie.js/issues/343) indicates the Docs have been updated in the Dexie  2.0.0-beta.2 Release notes. 

Are you planning on updating the dexie-mongoify master branch for Dexie V2? 

Also could you please include an unminified dexie.mongoify.js version in the dist folder.

Thanks.

**Comment by YurySolovyov** [comment]
@nevf if you can confirm that version from `dexie-2-support` works, I'll merge the PR soon and release the next version.

**Comment by nevf** [comment]
@YurySolovyov Yes I'm using the  ```dexie-2-support``` [dist](https://github.com/YurySolovyov/dexie-mongoify/tree/dexie-2-support/dist) release without any problems.

**Comment by YurySolovyov** [comment]
Thanks, I I'll do the release soon

**Comment by YurySolovyov** [comment]
@nevf sorry it took so long. Released v1.2.3. Feel free to close this if it works for you

**Comment by nevf** [comment]
@YurySolovyov Thanks, all good.  Could you please include an unminified ```dexie.mongoify.js``` version in the dist folder. I'm not into Webpack yet.

**Comment by YurySolovyov** [comment]
Sure, I'll ping you later
